SkinTab:NewLabel("Primary", "center")
local ARSkin = SkinTab:NewSelector("Assault Rifle", "None", {"AK-47", "AKEY-47", "Boneclaw Rifle"}, function(skin)
    skinlib:change("Assault Rifle", skin)
end)
local SniperSkin = SkinTab:NewSelector("Sniper", "None", {"Pixel Sniper", "Keyper", "Gingerbread Sniper", "Hyper Sniper"}, function(skin)
    skinlib:change("Sniper", skin)
end)
local CrossbowSkin = SkinTab:NewSelector("Crossbow", "None", {"Pixel Crossbow", "Frosty Crossbow"}, function(skin)
    skinlib:change("Crossbow", skin)
end)
SkinTab:NewLabel("Secondary", "center")
local HandGunSkin = SkinTab:NewSelector("Handgun", "None", {"Pixel Handgun", "Blaster", "Gingerbread Handgun", "Pumpkin Handgun", "Chainsaw"}, function(skin)
    skinlib:change("Handgun", skin)
end)
local RevolverSkin = SkinTab:NewSelector("Revolver", "None", {"Boneclaw Revolver", ""}, function(skin)
    skinlib:change("Revolver", skin)
end)
SkinTab:NewLabel("Melee", "center")
local KatanaSkin = SkinTab:NewSelector("Katana", "None", {"Pixel Katana", "Saber", "2025 Katana"}, function(skin)
    skinlib:change("Katana", skin)
end)
local KnifeSkin = SkinTab:NewSelector("Knife", "None", {"Candy Cane", "Karambit", "Chancla", "Machete", "Invisible"}, function(skin)
    skinlib:change("Knife", skin)
end)
